# Generated by Django 5.0.3 on 2024-05-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('speed', models.IntegerField(default=80)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(default=11),
        ),
    ]
