# Generated by Django 5.0.3 on 2024-05-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_car_student_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(max_length=20)),
                ('bike_model', models.CharField(max_length=100)),
                ('speed', models.IntegerField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.CharField(default='SUV', max_length=100),
        ),
    ]
